### ISSUE TITLE
inactive in v19 

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-apple-window-title-bar#2]
Hi,
The command is inactive on 4D v19, project mode
Thanks.

**Comment by miyako** [comment]
did you download .dmg from releases?

https://github.com/miyako/4d-plugin-apple-window-title-bar/releases/tag/1.1.0

**Comment by MatthieuLamp** [comment]
it's not ok

**Comment by MatthieuLamp** [comment]
strange
I tested on a new project in v19 and it works

**Comment by miyako** [comment]
thank you for the additional information. in any case, as explained in README, I recommended using the other plugin on v19 (you can do the same plus more).
